package com.mall.demo.model;

import lombok.Data;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table vendor
 *
 * @mbggenerated do_not_delete_during_merge
 */
@Data
public class Vendor implements Serializable {
    private Integer vendorId;

    private String vendorName;

    private String vendorDescrible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vendor
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vendorId=").append(vendorId);
        sb.append(", vendorName=").append(vendorName);
        sb.append(", vendorDescrible=").append(vendorDescrible);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}