package com.mall.demo.mapper;

import com.mall.demo.model.Vendor;
import com.mall.demo.model.VendorExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface VendorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int countByExample(VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int deleteByExample(VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer vendorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int insert(Vendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int insertSelective(Vendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    List<Vendor> selectByExample(VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    Vendor selectByPrimaryKey(Integer vendorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Vendor record, @Param("example") VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Vendor record, @Param("example") VendorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Vendor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vendor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Vendor record);
}